### ISSUE TITLE
Pub.dev packages review

### ISSUE THREAD

**Issue by sarika01** [atsign-foundation/at_widgets#342]
Lead: @ksanty 

Standard operating procedures for documentation [here](https://docs.google.com/document/d/1K4ytXLV99xQSLBmapZQlTn3--ZOzDw5M_a374AZ_7PE/edit)

The packages are published with updated documentation and example app. Links working

Please review the published version on pub.dev and provide feedback.

Also, any SEO keywords suggestion would be useful. See comments below. SEO and samples and examples pending.

- [x] [at_common_flutter](https://pub.dev/packages/at_common_flutter)
- [x] [at_onboarding_flutter](https://pub.dev/packages/at_onboarding_flutter)
- [x] [at_backupkey_flutter](https://pub.dev/packages/at_backupkey_flutter)
- [x] [at_contacts_flutter](https://pub.dev/packages/at_contacts_flutter)
- [x] [at_chat_flutter](https://pub.dev/packages/at_chat_flutter)
- [x] [at_events_flutter](https://pub.dev/packages/at_events_flutter)
- [x] [at_invitation_flutter](https://pub.dev/packages/at_invitation_flutter)
- [x] [at_location_flutter](https://pub.dev/packages/at_location_flutter)
- [x] [at_notify_flutter](https://pub.dev/packages/at_notify_flutter)
- [x] [at_sync_ui_flutter](https://pub.dev/packages/at_sync_ui_flutter)
- [x] [at_theme_flutter](https://pub.dev/packages/at_theme_flutter)

**Comment by ksanty** [comment]
at_common_flutter review:

- [x] Read and verify content for comprehension
- [x] Technical review of samples and examples @nickelskevin 
- [ ] SEO included (need to open a new ticket once we've identified keywords)
- [x] Spelling, grammar
- [x] Verify links / badges work properly

**Found Issue:**
- [ ] Review and check https://github.com/atsign-foundation/at_widgets/issues/384

@nickelskevin I'm unsure about where links should point to, they all work and things look great to me here.  Also unsure about SEO strategy and how we handle.

**Comment by ksanty** [comment]
at_onboarding_flutter review:

- [x] Read and verify content for comprehension
- [x] Technical review of samples and examples @nickelskevin 
- [ ] SEO included (need to open a new ticket once we've identified keywords)
- [x] Spelling, grammar
- [x] Verify links / badges work properly

**Found issues:**
- [x] PR #345 

@nickelskevin I'm unsure about where links should point to, they all work and things look great to me here.  Also unsure about SEO strategy and how we handle.

**Comment by ksanty** [comment]
at_backupkey_flutter review:

- [x] Read and verify content for comprehension
- [x] Technical review of samples and examples @nickelskevin 
- [ ] SEO included (need to open a new ticket once we've identified keywords)
- [x] Spelling, grammar
- [x] Verify links / badges work properly

**Found issues:**

- [x] PR #346 

@nickelskevin I'm unsure about where links should point to, they all work and things look great to me here.  Also unsure about SEO strategy and how we handle.

**Comment by ksanty** [comment]
at_contacts_flutter review:

- [x] Read and verify content for comprehension
- [x] Technical review of samples and examples @nickelskevin 
- [ ] SEO included  (need to open a new ticket once we've identified keywords)
- [x] Spelling, grammar
- [x] Verify links / badges work properly

**Found Issues:**

- [x]  PR #347 

@nickelskevin I'm unsure about where links should point to, they all work and things look great to me here.  Also unsure about SEO strategy and how we handle.

**Comment by xavierchanth** [comment]
@sarika01 The example for at_backupkey_flutter is not using null safety (trunk branch).

**Comment by sarika01** [comment]
@ksanty Adding some more packages which were updated for documentation. (reposted list in root above)

**Comment by ksanty** [comment]
at_chat_flutter review:

- [x] Read and verify content for comprehension
- [ ] SEO included  (need to open a new ticket once we've identified keywords)
- [x] Spelling, grammar
- [x] Verify links / badges work properly

**Comment by ksanty** [comment]
at_events_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

**Found issue:**
- [ ] Review and update this issue https://github.com/atsign-foundation/at_widgets/issues/380

**Comment by ksanty** [comment]
at_invitation_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

**Comment by ksanty** [comment]
at_location_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

**Found issue:**
- [ ] Review and update this issue https://github.com/atsign-foundation/at_widgets/issues/381

**Comment by ksanty** [comment]
at_notify_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

**Found issue:**
- [ ] Review and update this issue https://github.com/atsign-foundation/at_widgets/issues/382

**Comment by ksanty** [comment]
at_sync_ui_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

Found issue:
- [ ] Review and update this issue https://github.com/atsign-foundation/at_widgets/issues/383

**Comment by ksanty** [comment]
at_theme_flutter review:

- [x]  Read and verify content for comprehension
- [ ]  SEO included (need to open a new ticket once we've identified keywords)
- [x]  Spelling, grammar
- [x]  Verify links / badges work properly

**Comment by sarika01** [comment]
Some more package document correction is yet to be published. Hence, moving to next sprint.

**Comment by sarika01** [comment]
The pending packages have been published. @ksanty Please validate.

**Comment by yahu1031** [comment]
@sarika01 I see no info about getting an API for the app in the at_onboarding_widget package docs. Can you please have a look at that? (Hoping no need to raise another ticket for this)

**Comment by sarika01** [comment]
@yahu1031 Can you please elaborate on the requirement or the use-case that you are looking at?

**Comment by yahu1031** [comment]
There is no information on how to get the API key for the app in the at_onboarding_flutter package documentation. But in the code snippet, We mentioned that `API Key is mandatory for production environment.`. So need at least a line about how to get the API key(mail to `get-key@atsign.com`). We used to have it, but on the docs update, there are no traces of it.

**Comment by xavierchanth** [comment]
Closing as stale, we've done countless releases since this card has been worked on.
