### ISSUE TITLE
Restore static analysis for packages that are failing

### ISSUE THREAD

**Issue by cpswan** [atsign-foundation/at_widgets#769]
```[tasklist]
### Tasks
- [x] at_backupkey_flutter #761
- [x] at_chat_flutter #763
- [x] at_follows_flutter #764
- [x] at_invitation_flutter #765
- [x] at_location_flutter #766
- [x] at_login_flutter #767
- [x] at_sync_ui_flutter #768
```

**Comment by cpswan** [comment]
@Sardar1208 has set the status of the various linked issues to:

> needs deployment and validation. Assigning 0SP and moving to next sprint

So setting this to review and bumping to next PR.
